# Generated by Django 4.1.1 on 2022-10-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsportal',
            name='id_smart_process_cargo',
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='address_soap',
            field=models.URLField(default='https://iclient.1c-hosting.com/S0017033/S0017033_UNF_vn6er6vx9s/ws/apr_TsaSiteExchange?wsdl', help_text='Адрес сервера soap', verbose_name='Адрес сервера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='passwd_soap',
            field=models.CharField(default='2x3n4m', help_text='Пароль пользователя для аутентификации на сервере soap', max_length=255, verbose_name='Пароль пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='user_soap',
            field=models.CharField(default='exchange', help_text='Имя пользователя для аутентификации на сервере soap', max_length=50, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
