# Generated by Django 4.1.1 on 2022-10-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settingsportal_cargo_smart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsportal',
            name='airline_code',
            field=models.CharField(default='ufCrm3_1640060349', help_text='Код поля Авиакомпания в smart процессе Груз', max_length=30, verbose_name='Код поля Авиакомпания'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='count_position_code',
            field=models.CharField(default='ufCrm3_1639712970696', help_text='Код поля Количество мест в smart процессе Груз', max_length=30, verbose_name='Код поля Количество мест'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='number_awb_code',
            field=models.CharField(default='ufCrm3_1640060552', help_text='Код поля Номер авианакладной в smart процессе Груз', max_length=30, verbose_name='Код поля Номер авианакладной'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='route_in_code',
            field=models.CharField(default='ufCrm3_1662977544', help_text='Код поля Пункт отправки в smart процессе Груз', max_length=30, verbose_name='Код поля Пункт отправки'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='route_out_code',
            field=models.CharField(default='ufCrm3_1662977599', help_text='Код поля Пункт назначения в smart процессе Груз', max_length=30, verbose_name='Код поля Пункт назначения'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='weight_fact_code',
            field=models.CharField(default='ufCrm3_1639712999307', help_text='Код поля Вес фактический в smart процессе Груз', max_length=30, verbose_name='Код поля Вес фактический'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='weight_pay_code',
            field=models.CharField(default='ufCrm3_1639713016989', help_text='Код поля Вес к оплате в smart процессе Груз', max_length=30, verbose_name='Код поля Вес к оплате'),
        ),
    ]
