# Generated by Django 4.1.1 on 2022-10-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settingsportal_airline_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsportal',
            name='airline_code_code',
            field=models.CharField(default='PROPERTY_157', help_text='Код поля Код авиакомпании в универсальном списке', max_length=30, verbose_name='Код поля Код авиакомпании'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='airline_list_id',
            field=models.PositiveSmallIntegerField(default=39, help_text='ID универсального списка, в котором находится перечень авиакомпаний', verbose_name='ID универсального списка Авиакомпании'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='airline_name_code',
            field=models.CharField(default='PROPERTY_155', help_text='Код поля Наименование авиакомпании в универсальном списке', max_length=30, verbose_name='Код поля Наименование авиакомпании'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='city_code_code',
            field=models.CharField(default='PROPERTY_181', help_text='Код поля Код города в универсальном списке', max_length=30, verbose_name='Код поля Код города'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='city_country_code',
            field=models.CharField(default='PROPERTY_183', help_text='Код поля Страна города в универсальном списке', max_length=30, verbose_name='Код поля Страна города'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='city_list_id',
            field=models.PositiveSmallIntegerField(default=49, help_text='ID универсального списка, в котором находится перечень городов', verbose_name='ID универсального списка Города'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='city_name_code',
            field=models.CharField(default='NAME', help_text='Код поля Наименование города в универсальном списке', max_length=30, verbose_name='Код поля Наименование города'),
        ),
    ]
