# Generated by Django 4.1.1 on 2022-10-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_settingsportal_bill_number_in_1c_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsportal',
            name='link_get_print',
            field=models.URLField(default='https://iclient.1c-hosting.com/S0017033/S0017033_UNF_vn6er6vx9s/hs/apr_GetDocuments/download/', help_text='Основная часть ссылки для получения печатных форм документов', verbose_name='Ссылка на файл'),
        ),
    ]
