# Generated by Django 4.1.1 on 2022-11-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_settingsportal_link_get_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsportal',
            name='link_print_in_1c_code',
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='link_print_bill_code',
            field=models.CharField(default='UF_CRM_1665054289', help_text='Код поля Ссылка на счет в 1С в сделке', max_length=30, verbose_name='Код поля Ссылка на счет в 1С'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='link_print_bill_stamp_code',
            field=models.CharField(default='UF_CRM_1667785528', help_text='Код поля Ссылка на счет с подписью в 1С в сделке', max_length=30, verbose_name='Код поля Ссылка на счет с подписью в 1С'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='link_print_invoice_code',
            field=models.CharField(default='UF_CRM_1667785549', help_text='Код поля Ссылка на УПД в 1С в сделке', max_length=30, verbose_name='Код поля Ссылка на УПД в 1С'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='link_print_invoice_stamp_code',
            field=models.CharField(default='UF_CRM_1667785572', help_text='Код поля Ссылка на УПД с подписью в 1С в сделке', max_length=30, verbose_name='Код поля Ссылка на УПД с подписью в 1С'),
        ),
    ]
